-- ===========================================
-- 動態欄位管理系統 - FIELD_SETTINGS 表
-- ===========================================

-- 建立欄位設定表
CREATE TABLE FIELD_SETTINGS (
    FIELD_ID VARCHAR2(50) PRIMARY KEY,        -- 欄位 ID
    FIELD_NAME VARCHAR2(100) NOT NULL,        -- 資料庫欄位名稱
    DISPLAY_NAME VARCHAR2(200) NOT NULL,       -- 顯示名稱（中文）
    SHOW_IN_LIST CHAR(1) DEFAULT 'N',         -- 是否在列表頁顯示
    SHOW_IN_DETAIL CHAR(1) DEFAULT 'N',       -- 是否在詳情頁顯示
    SORT_ORDER NUMBER DEFAULT 0,              -- 排序順序
    FIELD_TYPE VARCHAR2(20) DEFAULT 'TEXT',   -- 欄位類型 (TEXT, DATE, NUMBER)
    IS_REQUIRED CHAR(1) DEFAULT 'N',          -- 是否為必要欄位
    DESCRIPTION VARCHAR2(500),                -- 欄位描述
    CREATED_DATE DATE DEFAULT SYSDATE,        -- 建立日期
    UPDATED_DATE DATE DEFAULT SYSDATE,        -- 更新日期
    CREATED_BY VARCHAR2(50),                 -- 建立者
    UPDATED_BY VARCHAR2(50)                  -- 更新者
);

-- 建立索引
CREATE INDEX IDX_FIELD_SETTINGS_ORDER ON FIELD_SETTINGS(SORT_ORDER);
CREATE INDEX IDX_FIELD_SETTINGS_LIST ON FIELD_SETTINGS(SHOW_IN_LIST);
CREATE INDEX IDX_FIELD_SETTINGS_DETAIL ON FIELD_SETTINGS(SHOW_IN_DETAIL);

-- ===========================================
-- 初始化欄位設定資料
-- ===========================================

-- 清除現有資料
DELETE FROM FIELD_SETTINGS;

-- 插入欄位設定資料
INSERT INTO FIELD_SETTINGS (
    FIELD_ID, FIELD_NAME, DISPLAY_NAME, SHOW_IN_LIST, SHOW_IN_DETAIL, SORT_ORDER, FIELD_TYPE, IS_REQUIRED, DESCRIPTION
) VALUES 
-- 基本資訊欄位
('RP_NO', 'OVC_RP_NO', '報告編號', 'N', 'Y', 1, 'TEXT', 'Y', '報告的唯一編號'),
('RP_NAME', 'OVN_RP_NAME', '報告名稱', 'Y', 'Y', 2, 'TEXT', 'Y', '報告的完整名稱'),
('SUMMARY', 'OVN_SUMMARY', '摘要', 'N', 'Y', 3, 'TEXT', 'N', '報告內容摘要'),
('MAIN_AUTHOR', 'OVN_RP_MAIN_AUTHOR', '主要作者', 'Y', 'Y', 4, 'TEXT', 'Y', '報告的主要作者'),
('AUTHOR_LIST', 'OVN_RP_AUTHOR_LIST', '所有作者', 'N', 'Y', 5, 'TEXT', 'N', '報告的所有作者列表'),
('AUTHOR_UNIT', 'OVN_RP_AUTHOR_UNIT', '主作者單位', 'Y', 'Y', 6, 'TEXT', 'N', '主要作者的所屬單位'),

-- 分類與性質欄位
('CSI_NAME', 'OVC_RP_CSI_NAME', '報告主號', 'Y', 'Y', 7, 'TEXT', 'N', '報告的主分類編號'),
('SUB_CSI_NAME', 'OVC_RP_SUB_CSI_NAME', '報告副號', 'Y', 'Y', 8, 'TEXT', 'N', '報告的副分類編號'),
('CAT_NAME', 'OVC_RP_CAT_NAME', '性質', 'Y', 'Y', 9, 'TEXT', 'N', '報告的性質分類'),
('TYPE_NAME', 'OVC_RP_TYPE_NAME', '分類', 'Y', 'Y', 10, 'TEXT', 'N', '報告的類型分類'),
('SECERT_LV_NAME', 'OVC_SECERT_LV_NAME', '機密等級', 'Y', 'Y', 11, 'TEXT', 'N', '報告的機密等級'),

-- 訓練相關欄位
('TRAIN_TYPE', 'OVN_RP_TRAIN_TYPE', '受訓類型', 'Y', 'Y', 12, 'TEXT', 'N', '報告的受訓類型'),
('CURRENT_DESC', 'OVN_RP_CURRENT_DESC', '現況敘述', 'N', 'Y', 13, 'TEXT', 'N', '目前的狀況描述'),
('APP_DESC', 'OVN_RP_APP_DESC', '應用敘述', 'N', 'Y', 14, 'TEXT', 'N', '應用情況描述'),

-- 日期欄位
('PUBLIC_DATE', 'ODT_PUBLIC_DATE', '發布日期', 'Y', 'Y', 15, 'DATE', 'Y', '報告的發布日期'),
('FIN_DATE', 'ODT_RP_FIN_DATE', '完成日期', 'N', 'Y', 16, 'DATE', 'N', '報告的完成日期'),

-- 狀態欄位
('STATUS_CDE', 'OVC_STATUS_CDE', '狀態碼', 'N', 'Y', 17, 'TEXT', 'Y', '報告的狀態代碼'),
('STATUS_NAME', 'OVC_STATUS_NAME', '狀態名稱', 'Y', 'Y', 18, 'TEXT', 'Y', '報告的狀態名稱'),

-- 其他可能欄位
('RP_KEYWORD', 'OVN_RP_KEYWORD', '關鍵字', 'N', 'Y', 19, 'TEXT', 'N', '報告的關鍵字'),
('RP_LANGUAGE', 'OVC_RP_LANGUAGE', '語言', 'N', 'Y', 20, 'TEXT', 'N', '報告的語言'),
('RP_PAGES', 'OVC_RP_PAGES', '頁數', 'N', 'Y', 21, 'NUMBER', 'N', '報告的頁數'),
('RP_ISBN', 'OVC_RP_ISBN', 'ISBN', 'N', 'Y', 22, 'TEXT', 'N', '報告的 ISBN 編號'),
('RP_PUBLISHER', 'OVN_RP_PUBLISHER', '出版單位', 'N', 'Y', 23, 'TEXT', 'N', '報告的出版單位')
;

-- 更新排序順序（確保正確的排序）
UPDATE FIELD_SETTINGS SET SORT_ORDER = 1 WHERE FIELD_ID = 'RP_NO';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 2 WHERE FIELD_ID = 'RP_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 3 WHERE FIELD_ID = 'SUMMARY';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 4 WHERE FIELD_ID = 'MAIN_AUTHOR';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 5 WHERE FIELD_ID = 'AUTHOR_LIST';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 6 WHERE FIELD_ID = 'AUTHOR_UNIT';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 7 WHERE FIELD_ID = 'CSI_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 8 WHERE FIELD_ID = 'SUB_CSI_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 9 WHERE FIELD_ID = 'CAT_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 10 WHERE FIELD_ID = 'TYPE_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 11 WHERE FIELD_ID = 'SECERT_LV_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 12 WHERE FIELD_ID = 'TRAIN_TYPE';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 13 WHERE FIELD_ID = 'CURRENT_DESC';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 14 WHERE FIELD_ID = 'APP_DESC';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 15 WHERE FIELD_ID = 'PUBLIC_DATE';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 16 WHERE FIELD_ID = 'FIN_DATE';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 17 WHERE FIELD_ID = 'STATUS_CDE';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 18 WHERE FIELD_ID = 'STATUS_NAME';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 19 WHERE FIELD_ID = 'RP_KEYWORD';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 20 WHERE FIELD_ID = 'RP_LANGUAGE';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 21 WHERE FIELD_ID = 'RP_PAGES';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 22 WHERE FIELD_ID = 'RP_ISBN';
UPDATE FIELD_SETTINGS SET SORT_ORDER = 23 WHERE FIELD_ID = 'RP_PUBLISHER';

-- 設定預設顯示狀態
-- 搜尋結果列表：預設勾選性質、分類、報告主號、機密等級、報告副號、受訓類型、主作者單位、主要作者
UPDATE FIELD_SETTINGS SET SHOW_IN_LIST = 'Y' WHERE FIELD_ID IN (
    'CAT_NAME', 'TYPE_NAME', 'CSI_NAME', 'SECERT_LV_NAME', 
    'SUB_CSI_NAME', 'TRAIN_TYPE', 'AUTHOR_UNIT', 'MAIN_AUTHOR'
);

-- 詳情頁：預設勾選全部欄位
UPDATE FIELD_SETTINGS SET SHOW_IN_DETAIL = 'Y';

-- 設定建立者資訊
UPDATE FIELD_SETTINGS SET CREATED_BY = 'SYSTEM', UPDATED_BY = 'SYSTEM';

COMMIT;

-- ===========================================
-- 驗證資料
-- ===========================================

-- 檢查插入的資料
SELECT COUNT(*) as total_fields FROM FIELD_SETTINGS;

-- 檢查列表顯示設定
SELECT FIELD_ID, DISPLAY_NAME, SHOW_IN_LIST, SORT_ORDER 
FROM FIELD_SETTINGS 
WHERE SHOW_IN_LIST = 'Y' 
ORDER BY SORT_ORDER;

-- 檢查詳情顯示設定
SELECT FIELD_ID, DISPLAY_NAME, SHOW_IN_DETAIL, SORT_ORDER 
FROM FIELD_SETTINGS 
WHERE SHOW_IN_DETAIL = 'Y' 
ORDER BY SORT_ORDER;
