-- 建立 DETAIL_VIEWS 表
-- 用於記錄書目詳情頁面的瀏覽統計

CREATE TABLE DETAIL_VIEWS (
    DOC_ID VARCHAR2(50) PRIMARY KEY,
    TITLE VARCHAR2(500) NOT NULL,
    VIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_VIEW_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 建立索引以提升查詢效能
CREATE INDEX IDX_DETAIL_VIEWS_COUNT ON DETAIL_VIEWS(VIEW_COUNT DESC);
CREATE INDEX IDX_DETAIL_VIEWS_TIME ON DETAIL_VIEWS(LAST_VIEW_TIME DESC);
CREATE INDEX IDX_DETAIL_VIEWS_TITLE ON DETAIL_VIEWS(TITLE);

-- 建立觸發程序（可選）：自動更新 LAST_VIEW_TIME
CREATE OR REPLACE TRIGGER TRG_DETAIL_VIEWS_TIME
BEFORE UPDATE ON DETAIL_VIEWS
FOR EACH ROW
BEGIN
    :NEW.LAST_VIEW_TIME := SYSTIMESTAMP;
END;
/

-- 插入一些範例資料（如果需要測試）
INSERT ALL
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC001', 'Oracle 資料庫管理手冊', 156)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC002', 'Python 程式設計入門', 234)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC003', '系統架構設計指南', 89)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC004', '網路安全實戰', 178)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC005', '雲端運算技術', 145)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC006', '大數據分析實務', 267)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC007', '人工智慧應用', 312)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC008', 'DevOps 實踐手冊', 198)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC009', '容器化技術', 223)
    INTO DETAIL_VIEWS (DOC_ID, TITLE, VIEW_COUNT) VALUES ('DOC010', '微服務架構', 189)
SELECT * FROM dual;

-- 提交變更
COMMIT;

-- 顯示建立結果
SELECT 
    DOC_ID,
    TITLE,
    VIEW_COUNT,
    TO_CHAR(LAST_VIEW_TIME, 'YYYY-MM-DD HH24:MI:SS') as LAST_VIEW
FROM DETAIL_VIEWS 
ORDER BY VIEW_COUNT DESC;

DBMS_OUTPUT.PUT_LINE('🎉 DETAIL_VIEWS 表建立完成！');
