-- 建立 SEARCH_HISTORY 表
-- 用於記錄所有搜尋操作的稽核資訊

CREATE TABLE SEARCH_HISTORY (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT VARCHAR2(50) NOT NULL,
    SEARCH_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODE VARCHAR2(20) NOT NULL,
    QUERY_DETAILS CLOB,
    RESULT_COUNT NUMBER(10),
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    SESSION_ID VARCHAR2(100),
    EXECUTION_TIME NUMBER(10,3),
    SUCCESS_FLAG CHAR(1) DEFAULT 'Y',
    ERROR_MESSAGE VARCHAR2(1000)
);

-- 建立索引以提升查詢效能
CREATE INDEX IDX_SEARCH_HISTORY_ACCOUNT ON SEARCH_HISTORY(ACCOUNT);
CREATE INDEX IDX_SEARCH_HISTORY_TIME ON SEARCH_HISTORY(SEARCH_TIME);
CREATE INDEX IDX_SEARCH_HISTORY_MODE ON SEARCH_HISTORY(MODE);
CREATE INDEX IDX_SEARCH_HISTORY_SUCCESS ON SEARCH_HISTORY(SUCCESS_FLAG);

-- 建立序列（如果 Oracle 版本不支援 GENERATED ALWAYS AS IDENTITY）
-- CREATE SEQUENCE SEQ_SEARCH_HISTORY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 建立觸發器（如果使用序列）
-- CREATE OR REPLACE TRIGGER TRG_SEARCH_HISTORY_ID
-- BEFORE INSERT ON SEARCH_HISTORY
-- FOR EACH ROW
-- BEGIN
--     :NEW.ID := SEQ_SEARCH_HISTORY_ID.NEXTVAL;
-- END;
-- /
